---
- name: Run script to install and setup postgreSQL
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Copy bash script to remote server
      copy:
        src: ~/exam_project/postgreSQL
        dest: ~/
        
    - name: Run script to install and setup postgres
      shell: bash ~/postgreSQL/psql.sh       
